spring:
  profiles:
    active: @profile.active@
    group:
      dev: share,cache
      prod: share,cache
  datasource:
    url: jdbc:mysql://localhost:3306/takeout?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root

server:
  port: 9000

mybatis-plus:
  # 实体类路径
  type-aliases-package: com.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
